on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - Connect and Deploy
      - uses: appleby/ssh-action@v1.0.3
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SSH_KEY}}
          port: 22
          script:
            cd ../home
            
            git reset --hard origin/main
            git pull origin main
            
            docker compose up -d --build
            
            docker image prune -f